config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'
  get 'welcome/index'

  get   '/help',  to: 'welcome#help'
  get   '/about', to: 'welcome#about'
  get   '/signup',to: 'users#new'
  post  '/signup',to: 'users#create'
  get   '/login', to: 'sessions#new'
  post  '/login', to: 'sessions#create'
  delete'/logout',to: 'sessions#destroy'
  get   'change_password', to: 'users#change_password'
  get   'reports',  to: 'reports#index'

  resources :listings do
    resources :messages
    resources :reports
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/models/listing.rb
class Listing < ApplicationRecord
    belongs_to :user
    has_many :reports, dependent: :destroy

    validates :title, presence: true, length: { minimum: 4 }
    validates :email, presence: true, length: { minimum: 4 }
    ISBN_REGEX = /(\A(?=(?:\D*\d){10}(?:(?:\D*\d){3})?$)[\d-]+\z)|(\A\z)/
    validates :isbn, format: { with: ISBN_REGEX }
    validates :condition, presence: true

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    
    before_action :check_cancel, :only => [:create, :edit]
    
    def new
        @listing = Listing.new
    end
    
    def index
        @listings = Listing.all
    end
    
    def edit
        @listing = Listing.find(params[:id])
    end
    
    def update
         @listing = Listing.find(params[:id])
        
        if @listing.update_attributes(listings_params)
            flash[:success] = "Listing succesfully updated"
            redirect_to user_path(current_user)
        else
            flash[:warning] = "There was an error while updating your listing."
            redirect_to edit_listing_path
        end
    end
    
    def create
        if logged_in?

            @listing = current_user.listings.build(listings_params)
            @listing.email = current_user.email
            
            if @listing.save
                flash[:success] = "Listing succesfully created."
                redirect_to @listing
            else
                render 'new'
            end
        else
            flash.now[:danger] = 'You must be logged in to perform that action.'
            redirect_to listings_path
        end
    end
    
    def show
        @listing = Listing.find(params[:id])
    end
    
    def destroy
        @listing = Listing.find(params[:id])
        @listing.destroy
        
        redirect_to listings_path
    end
    
    def current_listing
      @listing = Listing.find(params[:id])
    end
end


private 
    def has_reports?
        return @listing.reports.count != 0
    end
    
    def listings_params
        params.require(:listing).permit(:title, :isbn, :condition, :comments)
    end

    def check_cancel
        if params[:commit] == "Back"
            redirect_to listings_url
        end
    end

app/helpers/listings_helper.rb
module ListingsHelper
    def current_listing
      @listing = Listing.find(params[:id])
    end
end

app/views/listings/_listing.html.erb
<tr>
  <% if !current_user.nil? && listing.user_id == current_user.id %>
    <td><%= link_to listing.title, edit_listing_path(listing) %></td>
  <% else %>
    <td><%= link_to listing.title, listing_path(listing) %></td>
  <% end %>

  <td><%= listing.isbn %></td>
  <td><%= listing.condition %></td>

  <% if !current_user.nil? && listing.user_id == current_user.id %>
    <td><%= link_to 'Mark as sold', listing_path(listing), method: :delete, 
        data: { confirm: 'This will delete the listing, are you sure?'} %></td>
  <% else %>
    <% if logged_in? %>
      <td><%= link_to 'Report', new_listing_report_path(listing) %></td>
    <% end %>
  <% end %>
</tr>

app/views/listings/edit.html.erb
<div class="row justify-content-center w-100">
  <% provide(:title, @listing.title) %>
  <h1 class='text-primary'>Edit Listing</h1>
</div>
    
<div class="row w-50 justify-content-center">
  <div class='w-100'>
  <%= form_for(@listing) do |f| %>

    <% if @listing.errors.any? %>
        <h4>
          <%= pluralize(@listing.errors.count, "error") %> prohibited
              this article from being saved:
        </h4>
            <ul>
              <% @listing.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
    <% end %>
  
    <div class="m-2">
      <%= f.label :title %><br>
      <%= f.text_field :title, :class => 'w-100' %>
    </div>
  
    <div class="m-2">
      <%= f.label :isbn %><br>
      <%= f.text_field :isbn, :class => 'w-100' %>
    </div>
  
    <div class="m-2">
      <div class="radio">
        <%= f.label :condition %><br>
        <%= f.radio_button(:condition, "Perfect", :checked => true) %>
        <%= label_tag(:condition_perfect, "Perfect") %>
      </div>
      <div class="radio">
        <%= f.radio_button(:condition, "Good") %>
        <%= label_tag(:condition_good, "Good") %>
      </div>
      <div class="radio">
        <%= f.radio_button(:condition, "Worn") %>
        <%= label_tag(:condition_worn, "Worn") %>
      </div>
      <div class="radio">
        <%= f.radio_button(:condition, "Poor") %>
        <%= label_tag(:condition_poor, "Poor") %>
      </div>
    </div>
    
    <div class="m-2">
      <%= f.label :comments %><br>
      <%= f.text_area :comments, :class => 'form-control' %>
    </div>

  
    <div class="row justify-content-center m-2">
      <div class="col">
        <%= f.submit :Back, :class => "btn btn-outline-primary btn-block" %>
      </div>
      <div class="col">
        <%= f.submit 'Update Listing', :class => "btn btn-primary btn-block" %>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/listings/index.html.erb
<div class="row justify-content-center w-100">
  <% provide(:title, "Listings") %>
  <h1 class="text-primary">Book Listings</h1>
</div>

<div class="row w-100 m-0">
  <div class="table-responsive">
    <table id="dttb" class="table table-bordered table-hover table-condensed">
      <thead class="thead-light">
        <tr>
          <th>Title</th>
          <th>ISBN</th>
          <th>Condition</th>
          <% if logged_in? %>
            <th></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <%= render @listings %>
      </tbody>
    </table>
  </div>
</div>

app/views/listings/new.html.erb
<div class="row justify-content-center w-100">
  <% provide(:title, "New Listing") %>
  <h1 class='text-primary'>New Textbook Listing</h1>
</div>
    
<div class="row justify-content-center w-100">
  <%= form_for :listing, :html => { :class => "justify-content-center w-50" }, url: listings_path do |f| %>

    <% if @listing.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          The form contains <%= pluralize(@listing.errors.count, "error") %>.
        </div>
        <ul>
          <% @listing.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="m-2">
      <%= f.label :title %><br>
      <%= f.text_field :title, :class => 'w-100' %>
    </div>
  
    <div class="m-2">
      <%= f.label :isbn %><br>
      <%= f.text_field :isbn, :class => 'w-100' %>
    </div>
  
    <div class="m-2">
      <div class="radio">
        <%= f.label :condition %><br>
        <%= f.radio_button(:condition, "Perfect", :checked => true) %>
        <%= label_tag(:condition_perfect, "Perfect") %>
      </div>
      <div class="radio">
        <%= f.radio_button(:condition, "Good") %>
        <%= label_tag(:condition_good, "Good") %>
      </div>
      <div class="radio">
        <%= f.radio_button(:condition, "Worn") %>
        <%= label_tag(:condition_worn, "Worn") %>
      </div>
      <div class="radio">
        <%= f.radio_button(:condition, "Poor") %>
        <%= label_tag(:condition_poor, "Poor") %>
      </div>
    </div>
    
    <div class="m-2">
      <%= f.label :comments %><br>
      <%= f.text_area :comments, :class => 'form-control' %>
    </div>

  
    <div class="row justify-content-center m-2">
      <div class="col">
        <%= f.submit :Back, :class => "btn btn-outline-primary btn-block" %>
      </div>
      <div class="col">
        <%= f.submit :Submit, :class => "btn btn-primary btn-block" %>
      </div>
    </div>
  <% end %>
</div>

app/views/listings/show.html.erb
<div class="row justify-content-center w-100">
    <% provide(:title, @listing.title) %>
   <h1 class='text-primary'>
       <%= @listing.title %>
   </h1>
</div>

    <% if has_reports? %>
    <div class="w-100 p-3">
            <div class="alert alert-danger">
                    Careful! This listing has <%= @listing.reports.count %> 
                    reports. Use extra caution.
            </div>
        </div>
    <% end %>

<div class='row w-50 pb-2'>
    <div class= 'col-4'>
        
        
        <% if not @listing.isbn.blank? %>
            <div class="m-2">
                <h4>ISBN</h4>
                <%= @listing.isbn %>
            </div>
        <% end %>
    
        <div class="m-2">
            <h4>Condition</h4>
            <%= @listing.condition %>
        </div>
        
        <% if not @listing.comments.blank? %>
            <div class="m-2">
                <h4>Comments</h4>
                <%= @listing.comments %>
            </div>
        <% end %>
    </div>
</div>

        <div class="row justify-content-center w-100">
          <div class="col w-50">
            <%= button_to 'Back', listings_url, method: :get, :class => 'btn btn-outline-primary btn-block' %>
          </div>
          <div class="col w-50">
            <%= button_to 'Message', new_listing_message_url(@listing), method: :get, :class => 'btn btn-primary btn-block' %>
          </div>
        </div>
    </div>
</div>