config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'
  get 'welcome/index'

  get   '/help',  to: 'welcome#help'
  get   '/about', to: 'welcome#about'
  get   '/signup',to: 'users#new'
  post  '/signup',to: 'users#create'
  get   '/login', to: 'sessions#new'
  post  '/login', to: 'sessions#create'
  delete'/logout',to: 'sessions#destroy'
  get   'change_password', to: 'users#change_password'
  get   'reports',  to: 'reports#index'

  resources :listings do
    resources :messages
    resources :reports
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/models/user.rb
class User < ApplicationRecord
    has_many :listings
    attr_accessor :remember_token, :activation_token, :reset_token
    before_save :downcase_email
    before_create :create_activation_digest
    validates :fname, presence: true, length: { maximum: 50, minimum: 1}
    validates :lname, presence: true, length: { maximum: 50, minimum: 1}
    UNCC_EMAIL_REGEX = /\A[\w+\-.]+@uncc\.edu\z/i
    validates :email, presence: true, length: { maximum: 255 },
        format: { with: UNCC_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    
    # Returns the hash digest of the given string
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
            BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
    # Returns a random token.
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    
    # Remembers a user in the database for use in persistent sessions.
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    
    # Forgets a user
    def forget
        update_attribute(:remember_digest, nil)
    end
    
    # Returns true if the given token mathces the digest
    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end
    
    # Activates an account
    def activate
        update_columns(activated: true, activated_at: Time.zone.now)
    end
    
    # Sends activation email
    def send_activation_email
        UserMailer.account_activation(self).deliver_now
    end

    # Sends reset email
    def send_password_reset_email
        UserMailer.password_reset(self).deliver_now
    end
    
    # Returns true if a password reset has expired.
    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end
    
     
    # Creates and assigns a password reset token and digest
    def create_reset_digest
        self.reset_token = User.new_token
        update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
    end
    
    private
        # Converts email to all lower-case
        def downcase_email
            self.email = email.downcase
        end
        
        # Creates and assigns the activation token and digest
        def create_activation_digest
            self.activation_token = User.new_token
            self.activation_digest = User.digest(activation_token)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
    redirect_to root_url and return unless @user.activated?
  end  
  
  def new
    @user = User.new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
        
        if @user.update_attributes(user_params)
          flash[:success] = "Successfuly updated your user info"
          redirect_to user_path
        else
            flash[:warning] = "There was an error while updating your account."
            redirect_to edit_user_path
        end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.account_activation(@user).deliver
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    log_out if logged_in?
    @user.destroy
    flash[:success] = "User account succesfully deleted."
    redirect_to root_path
  end
  
  def change_password
    @user = User.find_by(id: current_user)
    @user.create_reset_digest
    redirect_to edit_password_reset_url(@user.reset_token, email: @user.email)
  end

  private
    def user_params
      params.require(:user).permit(:fname, :lname, :email, :password,
        :password_confirmation)
    end
    
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to new_session_path
      end
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!-- title text -->
<div class='row justify-content-center w-100'>
  <% provide(:title, "Edit Account") %>
  <h1 class='text-primary'>User Info</h1>
</div>

<div class="row w-50 justify-content-center pt-4">
  <div class="w-100">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label :fname, 'First Name' %>
      <%= f.text_field :fname, class: 'form-control' %>

      <%= f.label :lname, 'Last Name', class: 'pt-2' %>
      <%= f.text_field :lname, class: 'form-control' %>

      <%= f.submit "Update Info", class: "btn btn-primary btn-block mt-3" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<!-- title text -->
<div class='row justify-content-center w-100'>
  <% provide(:title, 'Sign up') %>
  <h1 class='text-primary'>Sign up</h1>
</div>

<div class="row w-50 justify-content-center pt-4">
  <div class="w-100">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>
    
      <%= f.label :fname, 'First Name' %>
      <%= f.text_field :fname, class: 'form-control' %>

      <%= f.label :lname, 'Last Name', class: 'pt-2' %>
      <%= f.text_field :lname, class: 'form-control' %>

      <%= f.label :email, class: 'pt-2' %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, class: 'pt-2' %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm Password", class: 'pt-2' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary btn-block mt-3" %>
      <p class='pt-1'>Already have an account? <%= link_to "Log in now!", login_path %></p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Your Account") %>

<div class= 'm-1 p-2 border' style="background-color:#e9ecef; border-color: #dee2e6; height: 100%">
  <h2 class='text-primary'>User Info</h2>
  <h5 style="margin: 10px 0px 0px 0px">First Name</h5>
  <%= @user.fname %>
  <h5 style="margin: 10px 0px 0px 0px">Last Name</h5>
  <%= @user.lname %>
  <h5 style="margin: 10px 0px 0px 0px">Email</h5>
  <%= @user.email %>
  <%= button_to 'Edit User Info', edit_user_path(current_user), :class => 'btn btn-primary btn-block my-2', :method => :get %>
  <%= button_to 'Change Password', change_password_url, :class => 'btn btn-primary btn-block my-2', :method => :get %>
  <%= button_to 'Delete Account', current_user, :class => 'btn btn-primary btn-block my-2', :method => :delete, data: {confirm: "Are you sure you want to delete your user account?" } %>
  <% if @user.admin? %>
    <%= button_to 'View Reports', reports_path, :class => 'btn btn-primary btn-block my-2', :method => :get %>
  <% end %>  
</div>

<div class='col'>
  <div class='row w-100 justify-content-center m-0'>
    <h2 class='text-primary'>Your Listings</h2>
  </div>
  <div class='row w-100 h-50 m-0'>
  <% if @user.listings.first.nil? %>
    <div class='col justify-content-center d-flex align-items-center'>
    <p class='text-center'>
      You do not have any listings yet, click <%= link_to 'here', new_listing_path %> to create one.<br>
      Once you have some listings, they will show up on this page.
    </p>
    </div>
  <% else %>
    <div class="row w-100 m-0">
      <div class="table-responsive">
        <table id="dttb" class="table table-bordered table-hover table-condensed">
          <thead class="thead-light">
            <tr>
              <th>Title</th>
              <th>ISBN</th>
              <th>Condition</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <%= render @user.listings %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
  </div>
</div>