config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'
  get 'welcome/index'

  get   '/help',  to: 'welcome#help'
  get   '/about', to: 'welcome#about'
  get   '/signup',to: 'users#new'
  post  '/signup',to: 'users#create'
  get   '/login', to: 'sessions#new'
  post  '/login', to: 'sessions#create'
  delete'/logout',to: 'sessions#destroy'
  get   'change_password', to: 'users#change_password'
  get   'reports',  to: 'reports#index'

  resources :listings do
    resources :messages
    resources :reports
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<!-- Title Text -->
<div class="column justify-content-center">
    <% provide(:title, "About") %>
    <h1 class="text-center text-primary">About</h1>

    <h2>What is UNCC Textbook Exchange?</h2>
    <p>
        UNCC Textbook Exchange is a convenient and safe platform for UNC
        Charlotte students to swap, sell, and purchase textbooks.
    </p>
    <h3>Why did we make it?</h3>
    <p>
        There are other sites such as Craigslist which allow users to
        buy and sell items free of charge, but what you sacrifice for cost
        and convenience is safety.  Look around online and there are 
        countless numbers of Craigslist horror stories ranging from awkward
        and weird to downright scary.  With our site we require that all 
        users have a valid UNCC email address, so you know you’re dealing 
        with one of your peers.
    </p>
    <h4>Who made it?</h4>
    <p>
        UNCC Textbook Exchange was made for our Spring 2019 ITSC 3155
        Software Engineering course.  Our team consists of Oliver King
        , Stefan Dybka, Bon Raj, Josh Williams, and Shrav Rajan.
    </p>
    <div class="d-flex justify-content-between p-3" >
      <%= image_tag("OliverK.png", class: "img-fluid") %>
      <%= image_tag("StefanD.png", class: "img-fluid") %> 
      <%= image_tag("BonaventureR.png", class: "img-fluid") %>
      <%= image_tag("JoshW.png", class: "img-fluid") %>
      <%= image_tag("BonaventureR.png", class: "img-fluid") %>
    </div>
</div>

app/views/welcome/help.html.erb
<!-- Title Text -->
<div class="column justify-content-center">
    <% provide(:title, "Help") %>
 <h1 class="text-center text-primary">Help</h1>

  <h2>How do I use UNCC Textbook Exchange safely?</h2>
  <p>We pride ourself in trying to make our application as safe as possible by 
  only allowing people with active UNC Charlotte emails to sign up.  With that 
  said you should still be aware safety measures to take when meeting up 
  with a stranger.</p>
    <ul>
        <li>Always meet in a well lit, populated area, we greatly encourage user
        to meet at the student union.</li>  
        <li>Always bring a friend with you, or let somone know
        where you're going and when you should be back.</li>
    <li>If selling, only take cash, or a secure app such as Venmo.  Never
    accept cashier checks, wire transfers, or money orders.</li>
    <li>Never give out personal or financial information.</li>
    <li>Never accept and IOU, or accept without seeing the item.  If a deal
    is too good to be true, it probably is.</li>
    <li>Never loan or rent an item.</li>
    <li>If you see an add that is suspicious or obviously a scam or fake, do not 
    contact the seller, just report the ad and we will take care of it.</li>
    </ul>
      <p><strong><font color="red"><center>UNCC Textbook Exchange accepts no responsibility for lost
    items or money</center></font></strong></p>
    
    <h3>How do I log in?</h3>
    <p>         
        To log in, all you have to do is click the login button, and enter your
        credentials.  If you haven't make an account with us yet click the "Sign up Now!"
        link and you will be taken to our sign up page.  After filling out your
        information using your UNCC email address, you will be sent a varification email, once you verify
        you will be ready to use the site! The activation email might have been sent to your spam folder.
    </p>


    <h4>How do I post my ad?</h4>
    <p>
    To post your textbook, click the "Post a new Listing" button.  This will
    take you to a page where you can enter your textbooks name, its isbn, its
    condition, and any additional comments relevant to the textbook.
     </p>

    <h4>How do I contact a user about a listing?</h4>
    <p>
    After viewing the book listings, click on a specific listing using the link under the title column.
    Then click the "Message" button. Type your message in the text box then click "Send Message". An email will 
    automatically be sent and that user can reply to your UNCC email address. Be sure to check your email for 
    any responses.
     </p>
</div>

app/views/welcome/index.html.erb
<!-- Title Text -->
<div class="row justify-content-center">
    <% provide(:title, "UNCC Textbook Exchange") %>
    <h1 class="text-center text-primary">Welcome to UNCC Textbook Exchange</h1>
    <h2 class="text-center">Swap, Sell, and Purchase Textbooks</h2>
</div>
        
<!-- Navigation Buttons -->
<div class="row justify-content-center w-60 btn-block">
    <%= button_to 'View All Listings', listings_path, :class => "btn btn-outline-primary btn-block mt-3", :method => :get %>
    <% if logged_in? %>
        <%= button_to 'Post A New Listing', new_listing_path, :class => "btn btn-outline-primary btn-block mt-3", :method => :get %>
        <%= button_to 'Your Listings', current_user, :class => "btn btn-outline-primary btn-block mt-3", :method => :get %>
    <% end %>
    <%= button_to 'About UNCC Textbook Exchange', about_path, :class => "btn btn-outline-primary btn-block mt-3", :method => :get %>
    <%= button_to 'Help', help_path, :class =>"btn btn-outline-primary btn-block mt-3", :method => :get %>
</div>