config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'
  get 'welcome/index'

  get   '/help',  to: 'welcome#help'
  get   '/about', to: 'welcome#about'
  get   '/signup',to: 'users#new'
  post  '/signup',to: 'users#create'
  get   '/login', to: 'sessions#new'
  post  '/login', to: 'sessions#create'
  delete'/logout',to: 'sessions#destroy'
  get   'change_password', to: 'users#change_password'
  get   'reports',  to: 'reports#index'

  resources :listings do
    resources :messages
    resources :reports
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <%= link_to 'UNCC Textbook Exchange', root_path, :class => 'navbar-brand' %>
      <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class='navbar-toggler-icon'></span>
      </button>
      
      <div class='collapse navbar-collapse' id='navbarSupportedContent'>
        <ul class='navbar-nav ml-auto'>
          <li class='nav-item'><%= link_to "Listings", listings_path, :class => 'nav-link active' %></li>
          <% if logged_in? %>
            <li class='nav-item'><%= link_to "New Listing", new_listing_path, :class => 'nav-link active' %></li>
            <li class='nav-item'><%= link_to "Your Account", current_user, :class => 'nav-link active' %></li>
            <li class='nav-item'><%= link_to "Log Out", logout_path, method: :delete, :class => 'nav-link active' %></li>
          </li>
          <% else %>
            <li class='nav-item'><%= link_to "Log In", login_path, :class => 'nav-link active' %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    
    
    <div class="container">
      <!-- Flash Messages -->
      <% flash.each do |message_type, message| %>
        <div class='alert alert-<%= message_type %> mt-2'>
          <%= message %>
        </div>
      <% end %>
      
      <!-- Main Page -->
      <div class="row shadow bg-white justify-content-center p-3 m-4">
        <%= yield %>
      </div>
    </div>
  </body>
  
  <script>
  $(document).ready(function() {
    $("#dttb").dataTable();
  });
  </script>

</html>